"""
Flask blueprint for the SPECTRE Logbook web app.
"""

from flask import Blueprint, jsonify, render_template, request, send_file
from app.spectre_backend import SpectreBackend

api = Blueprint("api", __name__)

backend = SpectreBackend()


@api.route("/")
def index():
    return render_template("index.html")


@api.route("/api/login", methods=["POST"])
def login():
    data = request.get_json(force=True)
    result = backend.start_session(data)
    return jsonify(result)


@api.route("/api/update", methods=["POST"])
def update():
    data = request.get_json(force=True)
    result = backend.update_metadata(data)
    return jsonify(result)


@api.route("/api/logout", methods=["POST"])
def logout():
    data = request.get_json(force=True)
    result = backend.save_and_logout(data)
    return jsonify(result)


@api.route("/api/lookup-email", methods=["POST"])
def lookup_email():
    data = request.get_json(force=True)
    email = data.get("email", "").strip()
    result = backend.lookup_email(email)
    return jsonify(result)


@api.route("/api/proposal-title/<code>")
def proposal_title(code):
    title = backend.get_proposal_title(code)
    return jsonify({"code": code, "title": title})


@api.route("/api/public-logs")
def public_logs():
    rows = backend.get_public_logs()
    return jsonify(rows)


@api.route("/api/admin-csv", methods=["POST"])
def admin_csv():
    data = request.get_json(force=True)
    password = data.get("password", "")
    csv_path = backend.get_admin_csv_path(password)
    if csv_path is None:
        return jsonify({"ok": False, "error": "Incorrect password or no CSV available."}), 403
    return send_file(csv_path, mimetype="text/csv", as_attachment=True,
                     download_name="spectre_admin_log.csv")


@api.route("/public-log")
def public_log_page():
    """Serve the standalone public log HTML (generated by the backend)."""
    import os
    html_path = os.path.join(backend.log_dir, "public_logs", "index.html")
    if os.path.exists(html_path):
        return send_file(html_path, mimetype="text/html")
    return "<h2>No public logs yet.</h2>", 200
